### PR TITLE
report gfortran polymorphic function assignment

### PR DESCRIPTION
**Pull request by everythingfunctional**

### CODE REVIEW

**Comment by everythingfunctional** [comment]
@ktras, if you have a minute, can you see if you can review and approve this?

**Review by ktras — COMMENTED** [review]
# Review Scope

- [x] Verify there is a single issue
- [x] Verify that the content is within a new, single folder with an appropriate path
- [x] Ensure the README contains the necessary information
- [x] Confirm issue can be reproduced

**Comment by ktras** [comment]
@everythingfunctional I don't think I have the right permissions to create a new label, but I think there should be a label `workaround` that can be applied to any report that includes a workaround for the bug, such as this one. Can you add that label or give me permissions?

**Comment by everythingfunctional** [comment]
@ktras, agreed. I've created and added that label.

**Review by ktras — APPROVED** [review]
LGTM. Thanks for adding the label!

**Pull request merged**
