### PR TITLE
NASA reproducer with ifx

### PR DESCRIPTION
**Pull request by tclune**

### CODE REVIEW

**Comment by tclune** [comment]
@everythingfunctional  A few suggestions for this repo:

1. Consider keeping the "fixed" items but in a separate directory.   Some issues come back.  Others rhyme ...
2. You may want to have a bit more of a schema for the metadata on the issues.  Nothing that would be mandatory, but a standard way to include things like:

```yaml
compiler: ifx
version: 2024.0
type: run-time # or compile-time
ticket:  # if available
```

**Review by everythingfunctional — COMMENTED** [review]
Thanks for the submission. I can confirm that the bug also exists for 2024.0.2. It would be worth noting that it only appears with the use of the `-fiopenmp` option **and** turning off optimization (though that's a bit less surprising as it might just be optimizing away the whole program).

**Comment by everythingfunctional** [comment]
Hey @tclune , thanks for the submission and suggestions.

> 1. Consider keeping the "fixed" items but in a separate directory.   Some issues come back.  Others rhyme ...

I've been going back and forth on this one. The fixed items are still "present" in the git history if anyone cares to look.

> 2\. You may want to have a bit more of a schema for the metadata on the issues.  Nothing that would be mandatory, but a standard way to include things like:

That seems reasonable. I'd welcome a PR for the directions :wink: .

**Comment by everythingfunctional** [comment]
> It would be worth noting that it only appears with the use of the `-fiopenmp` option **and** turning off optimization (though that's a bit less surprising as it might just be optimizing away the whole program).

@tclune , would you mind adding this to the description?

**Comment by tclune** [comment]
> @tclune , would you mind adding this to the description?

Done.

**Pull request merged**
